#!/usr/bin/env node
// 源卡 → 两侧产物。改完源卡跑一次，产物全部重生成。
// 源在 shared/roles/，共同契约在 shared/common-contract.md，产物一律不要手改。
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));
const ROLES = join(ROOT, "shared", "roles");
const CLAUDE_OUT = join(ROOT, "plugins", "ant-agent", "agents");
const CODEX_OUT = join(ROOT, "codex", "templates", ".codex", "agents");

// 八只共享的契约只维护这一份，改一处八只全变
const COMMON = readFileSync(join(ROOT, "shared", "common-contract.md"), "utf8").trim();

function parseFrontmatter(text, file) {
  const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(text);
  if (!m) throw new Error(`${file}: 缺 frontmatter`);
  const fm = {};
  let key = null;
  for (const line of m[1].split("\n")) {
    const kv = /^([a-z_]+):\s*(.*)$/.exec(line);
    if (kv) {
      key = kv[1];
      fm[key] = kv[2].trim() === ">-" ? "" : kv[2].trim();
    } else if (key && line.trim()) {
      fm[key] += (fm[key] ? " " : "") + line.trim();
    }
  }
  for (const need of ["slug", "model", "sandbox_mode", "color", "situation", "thought", "description"]) {
    if (!fm[need]) throw new Error(`${file}: frontmatter 缺 ${need}`);
  }
  return { fm, body: m[2].trim() };
}

// 下面这些字符串会写进产物，产物是模型读的，所以一律英文
const banner = (slug) =>
  `GENERATED by scripts/build.mjs from shared/roles/${slug}.md — do not edit`;

// 档位说明默认是「永远传这一档」。按活选档的角色（目前只有 adjust）用 model_rule 覆盖，
// 否则会生成「按活选 sonnet」加「Always pass model=haiku」这种自相矛盾的 description。
const descLine = (fm) =>
  `${fm.situation} ${fm.thought} ${fm.description} ` +
  (fm.model_rule || `Always pass model=${fm.model} explicitly when dispatching.`);

// description 里几乎必然出现「冒号 + 空格」，裸写进 YAML 会被当成 key 分隔符导致
// 整个 frontmatter 解析失败。折成块标量，块标量内容是纯文本，冒号在里面安全。
function yamlBlock(key, text, indent = "  ") {
  const lines = [];
  let cur = "";
  for (const w of text.split(/\s+/).filter(Boolean)) {
    if (cur && (cur + " " + w).length > 88) { lines.push(cur); cur = w; }
    else cur = cur ? cur + " " + w : w;
  }
  if (cur) lines.push(cur);
  return `${key}: >-\n${lines.map((l) => indent + l).join("\n")}`;
}

function assembleClaude({ fm, body }) {
  return `---
name: ant-${fm.slug}
${yamlBlock("description", descLine(fm))}
color: ${fm.color}
---

<!-- ${banner(fm.slug)} -->

# ant-${fm.slug}

${body}

---

${COMMON}
`;
}

function assembleCodex({ fm, body }) {
  const head = [
    "You are an ant-agent Codex Custom Agent, dispatched by the main session by situation.",
    `Custom Agent: ant-${fm.slug}`,
    `Suggested model: ${fm.model} tier. The main session passes \`model\` explicitly at`,
    "spawn_agent time; this file cannot set it.",
    `Workspace: ${fm.sandbox_mode}`,
  ].join("\n");

  const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

  return `# ${banner(fm.slug)}
name = "ant-${fm.slug}"
description = "${esc(fm.situation + " " + fm.thought)}"
sandbox_mode = "${fm.sandbox_mode}"
developer_instructions = """
${head}

${body}

---

${COMMON}
"""
`;
}

mkdirSync(CLAUDE_OUT, { recursive: true });
mkdirSync(CODEX_OUT, { recursive: true });

const files = readdirSync(ROLES).filter((n) => n.endsWith(".md")).sort();
if (!files.length) {
  console.error("✗ shared/roles/ 下没有源卡");
  process.exit(1);
}

for (const f of files) {
  const parsed = parseFrontmatter(readFileSync(join(ROLES, f), "utf8"), f);
  const slug = parsed.fm.slug;
  writeFileSync(join(CLAUDE_OUT, `ant-${slug}.md`), assembleClaude(parsed));
  writeFileSync(join(CODEX_OUT, `ant-${slug}.toml`), assembleCodex(parsed));
  console.log(`  ✓ ant-${slug}  ${parsed.fm.model.padEnd(6)} ${parsed.fm.sandbox_mode}`);
}
console.log(`\n生成 ${files.length} 只 × 2 侧`);
